import type {
  AIInsight,
  DoctorVisit,
  HealthScore,
  MedicalRecord,
  Measurement,
  TimelineEvent,
} from './types';

export const healthScoreData: HealthScore = {
  score: 88,
  trend: 'Stable',
  highlight: 'Excellent hydration and nutrition this week.',
  details: [
    'Fetal heartbeat strong',
    'Blood pressure within healthy range',
    'Balanced meal planning on track',
  ],
};

export const measurementsData: Measurement[] = [
  {
    id: 'm-1',
    label: 'Weight',
    value: '0',
    unit: 'kg',
    lastMeasuredDate: '',
  },
  {
    id: 'm-2',
    label: 'Blood Pressure',
    value: '0/0',
    unit: '',
    lastMeasuredDate: '',
  },
  {
    id: 'm-3',
    label: 'Heart Rate',
    value: '0',
    unit: 'bpm',
    lastMeasuredDate: '',
  },
  {
    id: 'm-4',
    label: 'Baby Growth',
    value: '0',
    unit: 'g',
    lastMeasuredDate: '',
  },
];

export const medicalRecordsData: MedicalRecord[] = [
  {
    id: 'rec-1',
    title: 'Ultrasound Scan',
    reportDate: '18 Jul 2026',
    reportType: 'ultrasound',
    summary: {
      plainEnglish: 'Healthy growth and amniotic fluid normal.',
      importantFindings: ['Growth appears normal.'],
      followUpActions: ['Schedule routine follow-up.'],
      questionsForDoctor: ['Please confirm the scan result timing.'],
    },
    metadata: {
      title: 'Ultrasound Scan',
      hospital: null,
      doctor: null,
      reportDate: '18 Jul 2026',
      pregnancyWeek: null,
    },
    measurements: {
      fetalHeartRate: null,
      crl: null,
      bpd: null,
      hc: null,
      ac: null,
      fl: null,
      estimatedFetalWeight: null,
      placenta: null,
      amnioticFluid: null,
      cervixLength: null,
      hemoglobin: null,
      bloodGroup: null,
      rhFactor: null,
      tsh: null,
      bloodSugar: null,
      vitaminD: null,
      vitaminB12: null,
      iron: null,
      bloodPressure: null,
      weight: null,
      other: {},
    },
    medicines: [],
    diagnosesMentioned: [],
    recommendations: [],
    nextVisit: null,
    confidence: 0.75,
    fileName: 'ultrasound-scan.pdf',
    reportUrl: '',
  },
  {
    id: 'rec-2',
    title: 'Blood Panel',
    reportDate: '12 Jul 2026',
    reportType: 'blood-test',
    summary: {
      plainEnglish: 'Iron levels good, vitamin D slightly low.',
      importantFindings: ['Vitamin D slightly low.'],
      followUpActions: ['Confirm supplement plan with provider.'],
      questionsForDoctor: ['Can you advise on the supplement plan?'],
    },
    metadata: {
      title: 'Blood Panel',
      hospital: null,
      doctor: null,
      reportDate: '12 Jul 2026',
      pregnancyWeek: null,
    },
    measurements: {
      fetalHeartRate: null,
      crl: null,
      bpd: null,
      hc: null,
      ac: null,
      fl: null,
      estimatedFetalWeight: null,
      placenta: null,
      amnioticFluid: null,
      cervixLength: null,
      hemoglobin: null,
      bloodGroup: null,
      rhFactor: null,
      tsh: null,
      bloodSugar: null,
      vitaminD: null,
      vitaminB12: null,
      iron: null,
      bloodPressure: null,
      weight: null,
      other: {},
    },
    medicines: [],
    diagnosesMentioned: [],
    recommendations: [],
    nextVisit: null,
    confidence: 0.7,
    fileName: 'blood-panel.pdf',
    reportUrl: '',
  },
  {
    id: 'rec-3',
    title: 'Glucose Test',
    reportDate: '03 Jul 2026',
    reportType: 'blood-test',
    summary: {
      plainEnglish: 'Awaiting lab confirmation.',
      importantFindings: [],
      followUpActions: ['Await lab confirmation.'],
      questionsForDoctor: ['When will the results be available?'],
    },
    metadata: {
      title: 'Glucose Test',
      hospital: null,
      doctor: null,
      reportDate: '03 Jul 2026',
      pregnancyWeek: null,
    },
    measurements: {
      fetalHeartRate: null,
      crl: null,
      bpd: null,
      hc: null,
      ac: null,
      fl: null,
      estimatedFetalWeight: null,
      placenta: null,
      amnioticFluid: null,
      cervixLength: null,
      hemoglobin: null,
      bloodGroup: null,
      rhFactor: null,
      tsh: null,
      bloodSugar: null,
      vitaminD: null,
      vitaminB12: null,
      iron: null,
      bloodPressure: null,
      weight: null,
      other: {},
    },
    medicines: [],
    diagnosesMentioned: [],
    recommendations: [],
    nextVisit: null,
    confidence: 0.65,
    fileName: 'glucose-test.pdf',
    reportUrl: '',
  },
];

export const doctorVisitsData: DoctorVisit[] = [
  {
    id: 'visit-1',
    provider: 'Dr. Mehta',
    specialty: 'Obstetrics',
    date: '25 Jul 2026',
    note: 'Discuss nutrition and scan results.',
  },
  {
    id: 'visit-2',
    provider: 'Dr. Lee',
    specialty: 'Nutritionist',
    date: '01 Aug 2026',
    note: 'Review supplement plan and meal prep.',
  },
];

export const aiInsightsData: AIInsight[] = [
  {
    id: 'insight-1',
    title: 'Sleep rhythm looks strong',
    description: 'Your rest pattern is consistent, supporting recovery and growth.',
  },
  {
    id: 'insight-2',
    title: 'Hydration milestone reached',
    description: 'You met your hydration goal for 5 days in a row this week.',
  },
  {
    id: 'insight-3',
    title: 'Gentle activity recommended',
    description: 'Try a 15-minute walk after meals to ease digestion.',
  },
];

export const pregnancyTimelineData: TimelineEvent[] = [
  {
    id: 'event-1',
    week: 'Week 20',
    date: '17 Jul 2026',
    title: 'Anatomy scan complete',
    status: 'Done',
  },
  {
    id: 'event-2',
    week: 'Week 22',
    date: '25 Jul 2026',
    title: 'Doctor visit scheduled',
    status: 'Upcoming',
  },
  {
    id: 'event-3',
    week: 'Week 24',
    date: '05 Aug 2026',
    title: 'Nutrition review',
    status: 'Planned',
  },
];
